# Generated by Django 5.2.8 on 2025-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0002_user_userdata_alter_testmodel_name_creatorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
